package com.jobmatcher.server.model;

public enum ErrorCode {
    AUTH_INVALID,
    EMAIL_EXISTS,
    RESOURCE_NOT_FOUND,
    DATABASE_ERROR,
    INTERNAL_ERROR,
    VALIDATION_FAILED,
    METHOD_NOT_ALLOWED,
    PASSWORD_RECOVERY_FAILED,
    EMAIL_SENDING_FAILED,
    GMAIL_API_ERROR,
    TOKEN_CREATION_FAILED,
    FILE_UPLOAD_FAILED,
    UNSUPPORTED_MEDIA_TYPE,
    ACCESS_DENIED,
    INVALID_DATE_FORMAT,
    INVALID_PROJECT_OPERATION,
    INVALID_OPERATION
}
