import http from "k6/http";
import { sleep, check, group } from "k6";

export const options = {
  stages: [
    { duration: "1m", target: 250 },
    { duration: "2m", target: 500 },
    { duration: "3m", target: 1000 },
    { duration: "2m", target: 250 },
    { duration: "1m", target: 0 },
  ],
  thresholds: {
    http_req_duration: ["p(95)<800"],
    http_req_failed: ["rate<0.01"],
  },
};
/* export const options = {
  stages: [
    { duration: "30s", target: 20 },
  ],
  thresholds: {
    http_req_duration: ["p(95)<800"],
    http_req_failed: ["rate<0.01"],
  },
}; */

const BASE_URL = "http://localhost:8080/api/v0";
const USERS = Array.from({ length: 1000 }, (_, i) => ({
  email: `user${i}@jobmatcher.com`,
  password: "Password!23",
}));

const vuState = {};

export default function () {
  const projectsList = [];
  const contractsList = [];
  const jobFeedProjectsList = [];

  const user = USERS[(__VU - 1) % USERS.length];

  // --- LOGIN PHASE ---
  if (!vuState[__VU]) {
    const loginRes = http.post(
      `${BASE_URL}/auth/login`,
      JSON.stringify({
        email: user.email,
        password: user.password,
      }),
      { headers: { "Content-Type": "application/json" } }
    );

    check(loginRes, { "login succeeded": (r) => r.status === 200 });
    const token = loginRes.json("token");
    const authUser = loginRes.json("user");
    const headers = { Authorization: `Bearer ${token}` };

    // Fetch the customer/freelancer profile
    // CUSTOMER branch
    if (authUser.role === "CUSTOMER") {
      const profileRes = http.get(
        `${BASE_URL}/profiles/customers/users/${authUser.id}`,
        { headers }
      );

      check(profileRes, { "fetched profile": (r) => r.status === 200 });
      const profileData = profileRes.json();
      const profileId = profileData.profileId;

      vuState[__VU] = { token, role: authUser.role, profileId, proposals: [] };
      sleep(Math.random() * 3 + 2); // Simulate think time
    }

    // STAFF branch
    else if (authUser.role === "STAFF") {
      const profileRes = http.get(
        `${BASE_URL}/profiles/freelancers/users/${authUser.id}`,
        { headers }
      );

      check(profileRes, { "fetched profile": (r) => r.status === 200 });
      const profileData = profileRes.json();
      const profileId = profileData.profileId;

      vuState[__VU] = { token, role: authUser.role, profileId, proposals: [] };
      sleep(Math.random() * 3 + 2); // Simulate think time
    }

    // --- MAIN ACTION PHASE ---
    const { role, profileId, proposals } = vuState[__VU];

    group("User Activity", function () {
      // Fetch contracts
      const contracts = http.get(`${BASE_URL}/contracts?page=0&size=50`, {
        headers,
      });
      check(contracts, { "fetched contracts": (r) => r.status === 200 });
      contractsList.push(...(contracts.json().content || []));
      sleep(Math.random() * 3 + 2); // Simulate think time

      // Fetch user's projects
      const projects = http.get(`${BASE_URL}/projects?page=0&size=50`, {
        headers,
      });
      check(projects, { "fetched projects": (r) => r.status === 200 });
      projectsList.push(...(projects.json().content || []));
      sleep(Math.random() * 3 + 2); // Simulate think time

      //Fetch job-feed
      const jobFeedProjects = http.get(
        `${BASE_URL}/projects/job-feed?page=0&size=50`,
        {
          headers,
        }
      );
      check(jobFeedProjects, { "fetched job feed": (r) => r.status === 200 });
      jobFeedProjectsList.push(...(jobFeedProjects.json().content || []));
      sleep(Math.random() * 3 + 2); // Simulate think time

      // --- Conditional actions ---
      // Create project (CUSTOMER only)
      if (Math.random() < 0.5 && role === "CUSTOMER") {
        const payload = {
          customerId: profileId,
          title: `LoadTest Project ${Math.floor(Math.random() * 10000)}`,
          description: "Generated by k6",
          budget: Math.floor(Math.random() * 5000) + 500,
          paymentType: "UPON_COMPLETION",
          deadline: "2026-11-03",
          categoryId: 1,
          subcategoryIds: [1],
        };

        const res = http.post(`${BASE_URL}/projects`, JSON.stringify(payload), {
          headers: { ...headers, "Content-Type": "application/json" },
        });

        check(res, {
          "project created successfully": (r) => [200, 201].includes(r.status),
        });
        sleep(Math.random() * 3 + 2); // Simulate think time
      }

      // Create proposal (STAFF only)
      if (
        Math.random() < 0.3 &&
        role === "STAFF" &&
        jobFeedProjectsList.length > 0
      ) {
      let selectedProject = jobFeedProjectsList[
        Math.floor(Math.random() * jobFeedProjectsList.length)
      ];

      if(selectedProject.status === "OPEN"){
        const payload = {
          projectId: selectedProject.id,
          freelancerId: profileId,
          coverLetter: "k6 proposal",
          amount: Math.floor(Math.random() * 5000) + 500,
          estimatedDuration: Math.floor(Math.random() * 30) + 5,
          plannedStartDate: "2025-11-03T12:00:00Z",
          plannedEndDate: "2025-12-10T12:00:00Z",
        };

        const res = http.post(
          `${BASE_URL}/proposals`,
          JSON.stringify(payload),
          {
            headers: { ...headers, "Content-Type": "application/json" },
          }
        );

        check(res, {
          "proposal created successfully": (r) =>
            [200, 201, 400].includes(r.status),
        });

        if ([200, 201].includes(res.status)) proposals.push(res.json());
        if (![200, 201, 400].includes(res.status)) {
          console.error(
            `❌ Proposal failed: ${res.status} — ${
              res.body ? res.body : "(no body)"
            }`
          );
        }
      }
        sleep(Math.random() * 3 + 2); // Simulate think time
      }

      // Update proposal status (CUSTOMER only)
      if (Math.random() < 0.5 && role === "CUSTOMER") {
        // Fetch customer's own open projects
        const myProjectsRes = http.get(
          `${BASE_URL}/projects?page=0&size=20&status=OPEN`,
          { headers }
        );

        check(myProjectsRes, {
          "fetched my projects": (r) => r.status === 200,
        });

        const myProjects = myProjectsRes.json().content || [];

        // Loop through projects until a pending proposal is found
        for (const project of myProjects) {
          // Fetch pending proposals for this project using the correct endpoint
          const proposalsRes = http.get(
            `${BASE_URL}/proposals?projectId=${project.id}&status=PENDING&page=0&size=20`,
            { headers }
          );

          check(proposalsRes, {
            "fetched project proposals": (r) => r.status === 200,
          });

          const pendingProposals = proposalsRes.json().content || [];

          if (pendingProposals.length > 0) {
            const proposal = pendingProposals[0]; // pick the first pending proposal

            // Accept proposal
            const updateRes = http.patch(
              `${BASE_URL}/proposals/status/${proposal.id}`,
              JSON.stringify({ status: "ACCEPTED" }),
              { headers: { ...headers, "Content-Type": "application/json" } }
            );

            check(updateRes, {
              "proposal accepted successfully": (r) => r.status === 200,
            });

            sleep(Math.random() * 3 + 2); // Simulate think time
            break; // stop the loop after updating one proposal
          }
        }
      }

      // Fetch user's proposals (STAFF only)
      if (Math.random() < 0.9 && role === "STAFF") {
        const myProposals = http.get(`${BASE_URL}/proposals/freelancer/${profileId}`, { headers });
        check(myProposals, { "fetched my proposals": (r) => r.status === 200 });
        const proposalsData = myProposals.json().content || [];
        proposals.push(...proposalsData);

        for (const proposal of proposalsData) {
          if(proposal.status === "ACCEPTED") {
            let projectId = proposal.projectId;
            // Fetch contract details for accepted proposal
            const contractRes = http.get(
              `${BASE_URL}/contracts/project/${projectId}`,
              { headers }
            );

            check(contractRes, {
              "fetched contract for accepted proposal": (r) => r.status === 200,
            });
          }
          break;
        }
        sleep(Math.random() * 3 + 2); // Simulate think time
      }
    });
  }
}
